### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

### ISSUE THREAD

**Issue by NikitaBeloglazov** [NikitaBeloglazov/clipman#16]
## Bug info / steps to reproduce / versions
wl-clipboard version: 2.2.1
Happens when you copy a picture, a ytcon crashes
Bug found by @dgudim (thanks 🙏)

It seems this is because wl-clipboard is now working with images by default, and I did not excepted this behaviour.
**A fix is ​​needed**

## Full Traceback:
```python3
An unknown error has occurred!

Traceback (most recent call last):
  File "/home/kloud/Downloads/ytcon/src/ytcon/misc/clipboard.py", line 89, in clipboard_checker
    new_clip = clipman.paste()
               ^^^^^^^^^^^^^^^
  File "/home/kloud/Downloads/ytcon/venv/lib/python3.12/site-packages/clipman/__init__.py", line 237, in get
    return call("get")
           ^^^^^^^^^^^
  File "/home/kloud/Downloads/ytcon/venv/lib/python3.12/site-packages/clipman/__init__.py", line 285, in call
    return run_command(['wl-paste'], features=("wl-clipboard_nothing_is_copied_is_ok",))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kloud/Downloads/ytcon/venv/lib/python3.12/site-packages/clipman/__init__.py", line 82, in run_command
    return runner.stdout.decode("UTF-8").removesuffix("\n") # looks like all commands returns \n in the end
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

Printed by exit_with_exception()
```

**Comment by NikitaBeloglazov** [comment]
## Fixed in [v3.2.5](https://github.com/NikitaBeloglazov/clipman/releases/tag/v3.2.5)
If the problem still occurs, please update clipman, and if it does not help, reopen the issue
